### ISSUE TITLE
Drop the legacy `Result` serialization behavior in 5.x

### ISSUE THREAD

**Issue by itegulov** [near/near-sdk-rs#749]
Something to consider for 5.x (or another major release): 
 1\. Making [https://github.com/near/near-sdk-rs/pull/745](https://github.com/near/near-sdk-rs/pull/745) the default behavior for all functions that return `Result`
 2\. Deleting `#[handle_result]` annotation
 3\. Removing compilation error introduced in #748

**Comment by uint** [comment]
Following the discussion in https://github.com/near/near-sdk-rs/pull/1057#discussion_r1272593025, I don't think we're going to do this. Should we close this, @frol @agostbiro?

**Comment by uint** [comment]
David Tolnay invented [a way to emulate specialization](https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md) that basically abuses [deref coercion](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/second-edition/ch15-02-deref.html#implicit-deref-coercions-with-functions-and-methods).

This weekend, I figured out a way to use this to [emulate associated functions with trait specialization](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=92a13d8edc91fef7e2b8e7f780e46aa1).

This looks like a promising way to reliably detect `Result<_, _>` types in macro expansions, including for the purposes of generating schemas. I might experiment with that sometime soon.

**Comment by frol** [comment]
@uint Oh, I missed the previous comment, sorry. Well, if we can do that and the UX won't be confusing, I am all ears!
