### ISSUE TITLE
Compilation error due to duplicate definitions for 'contract_source_metadata*

### ISSUE THREAD

**Issue by frol** [near/near-sdk-rs#1117]
![IMG_8574](https://github.com/near/near-sdk-rs/assets/304265/2228cfd7-1579-40be-a8d0-804381ecee52)

This happens when #[near_bindgen] is used several times (which is totally valid use case)

This is caused by https://github.com/near/near-sdk-rs/pull/1106 and only affects 5.0.0-alpha.1 release and onwards.

This blocks 5.0 stable release.
